version: 0.0

os: linux 

files:
  - source: /
    destination: /home/ubuntu/avery/dev/frontend
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: deployment-scripts/BeforeInstallHook.sh
      timeout: 300
  AfterInstall:
    - location: deployment-scripts/BeforeInstallHook.sh
      timeout: 1000